app1/urls.py
from django.urls import path
from app1.views import*
app_name='app1'
urlpatterns=[
    path('third/',third,name='third'),
]

specific_urlproject/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/',first,name='first'),
    path('second/',second,name='second'),
    path('third/',include('app1.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request, 'first.html')

def second(request):
    return render(request, 'second.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def third(request):
    return render(request, 'third.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>specific_url</title>
</head>
<body>
    <center>
        <h1> we can see first html pages </h1>
        <a href="{% url 'second' %}">go to second page </a>
        <h1></h1>
        <a href="{% url 'app1:third' %}">go to third page </a>
    </center>
    
</body>
</html>

templates/html file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center> 
        <h1 align="right"> using attribute align </h1>
        <h2 align="center"> using attribute align </h2>
        <h3 align="left"> using attribute align </h3>
    </center>
    
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> second html page </h1>
        <a href="{% url 'first' %}"> go to first </a>
        <h1></h1>
        <a href="{% url 'app1:third' %}"> go to third </a>
    </center>
    
</body>
</html>

templates/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center> 
        <h1> third html page </h1>
        <a href="{% url 'first' %}"> go to first </a>
        <h1></h1>
        <a href="{% url 'second' %}"> go to second </a>
    </center>
    
</body>
</html>